variables:
  CI_REGISTRY_NAME: "graphql-docker.maven.dev.tripadvisor.com"
  CI_REGISTRY_IMAGE: "taql"

default:
  image: node:16.18.0

stages:
  - test
  - docker

test:
  stage: test
  cache:
    key: $CI_COMMIT_REF_NAME
    when: 'always'
    paths:
      - .yarn/cache/
  script:
    - ./scripts/ci.bash

docker-test:
  stage: test
  only:
    - merge_requests
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --cache=false
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_NAME}/${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --label org.label-schema.build-date=$(date +%Y%m%d)
      --label org.label-schema.description="$CI_PROJECT_TITLE"
      --label org.label-schema.license="TripAdvisor Proprietary"
      --label org.label-schema.name="$CI_PROJECT_NAME"
      --label org.label-schema.schema-version=1.0
      --label org.label-schema.vcs-ref="$CI_COMMIT_SHA"
      --label org.label-schema.vcs-url="$CI_PROJECT_URL"
      --label org.label-schema.vendor=TripAdvisor
      --verbosity=info
      --no-push
