default:
  image: node:16.18.0

stages:
  - test
  - docker

test:
  stage: test
  cache:
    key: $CI_COMMIT_REF_NAME
    when: 'always'
    paths:
      - .yarn/cache/
  script:
    - ./scripts/ci.bash

docker-nopush:
  variables:
    CI_REGISTRY_IMAGE: "graphql-docker.maven.dev.tripadvisor.com/taql"
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --no-push
