nodeLinker: node-modules

npmRegistryServer: 'https://maven.dev.tripadvisor.com/artifactory/api/npm/yarn'

npmScopes:
  ta-graphql-utils:
    npmRegistryServer: 'https://gitlab.dev.tripadvisor.com/api/v4/projects/16433/packages/npm'
  gsr:
    npmRegistryServer: 'https://gitlab.dev.tripadvisor.com/api/v4/projects/15885/packages/npm'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.4.cjs
